### ISSUE TITLE
Parsing double coordinates depends on locale

### ISSUE THREAD

**Issue by PimenovAlexander** [CauldronDevelopmentLLC/CAMotics#100]
Dear developers, 
  there seem to a bug in parsing double values in locales in which comma is used as separator instead of the point for example ru_RU.UTF-8 ua_UA.UTF-8 etc. 
    During tokenization in (Tokenizer.cpp) only digits and "." are allowed, but afterwards in Parser.cpp:Parser::number()  String::parseDouble() is used to actually convert string to double.
   In it's turn String::parseDouble()  uses strtod() which is locale dependant. 

So an attempt to parse "6.2" in ru_RU.UTF-8 leads to actually getting "6" because in this locale strtod() expects comma is separator. This is obviously critical for any machining, especially in arcs.

I suggest
  1. Workaround - Force locale to C by setting  export LC_NUMERIC="C"
  2. Give up using String::parseDouble() because it does not what you want, it parses double in locale format, while we want to parse double according to GCODE format. Probably actual string to double conversion could be done in Tokenizer because it knows what it actually is and knows and is responsible for the presentation format.

Best regards,
Alexander

**Comment by jcoffland** [comment]
Fixed in 1.0.0 release.
