### ISSUE TITLE
Build error: No tool named 'config': not a Zip file: . . .

### ISSUE THREAD

**Issue by michaelfranzl** [CauldronDevelopmentLLC/CAMotics#106]
"cbang" compilation succeeded with `scons`, but building OpenSCAM with `scons` fails immediately with the following message:

```
scons: Reading SConscript files ...
EnvironmentError: No tool named 'config': not a Zip file:
  File "/media/projects/cnc/software/OpenSCAM/SConstruct", line 13:
    env.Tool('config', toolpath = [cbang])
  File "/usr/lib/scons/SCons/Environment.py", line 1786:
    tool = SCons.Tool.Tool(tool, toolpath, **kw)
  File "/usr/lib/scons/SCons/Tool/__init__.py", line 97:
    module = self._tool_module()
  File "/usr/lib/scons/SCons/Tool/__init__.py", line 157:
    raise SCons.Errors.EnvironmentError(m)
```

The build used to work for me in Debian Wheezy, so something has changed, but I'm not familiar enough with the scons building system.

**Comment by kigwaini** [comment]
So how DID you resolve the error?

I have the same issue and tried running the "export CBANG_HOME=$PWD/cbang" from root and home directories and still CAMotics won't compile

**Comment by jcoffland** [comment]
@kigwaini you have to be in the right directory when you run ``export CBANG_HOME=$PWD/cbang``.  ``$PWD`` is an environment variable that contains the current directory.  If you follow the commands in the README *exactly* then it will work.  If you change directories or run in a new terminal it is likely to fail.  One test you can do is to run this command ``ls $CBANG_HOME``.  If that does not produce a list of the contents of the ``cbang`` directory then you do not have the environment variable ``CBANG_HOME`` set correctly.

**Comment by kigwaini** [comment]
Thanx for the reply. 

the command "ls $CBANG_HOME"  shows the contents of the folder 
then I type "cd CAMotics" press ENTER
and then "sudo scons"  and the error returns

I followed the instructions in the "readme" exactly. or does cloning both cbang and CAMotics first and then running the commands constitute a deviation from the instructions?

I will delete the files and start over again see how it goes

**Comment by kigwaini** [comment]
same error as before

EnvironmentError: No tool named 'config': not a Zip file:
  File "/home/stevecnc/CAMotics/SConstruct", line 14:
    env.Tool('config', toolpath = [cbang])
  File "/usr/lib/scons/SCons/Environment.py", line 1782:
    tool = SCons.Tool.Tool(tool, toolpath, **kw)
  File "/usr/lib/scons/SCons/Tool/__init__.py", line 94:
    module = self._tool_module()
  File "/usr/lib/scons/SCons/Tool/__init__.py", line 154:
    raise SCons.Errors.EnvironmentError(m)

**Comment by kigwaini** [comment]
installing the .deb package creates an Item in the Applications menu but nothing happens when I click on it.

**Comment by kigwaini** [comment]
when I run the ./camotics in the "/usr/bin" directory, I get the following error.

./camotics: /lib/i386-linux-gnu/i686/cmov/libm.so.6: version `GLIBC_2.15' not found (required by ./camotics)
./camotics: /usr/lib/i386-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by ./camotics)

is it just me or was CAMotics never meant to work on debian wheezy

**Comment by jcoffland** [comment]
CAMotics works fine on Wheezy.  The packages are compiled on Testing which is currently equivalent to Stretch which uses a newer glibc.  I need help getting CAMotics accepted as a Debian package which would solve much of the problem.

Why did you add ``sudo`` to ``scons``?  ``sudo`` discards all the environment variable settings and it's not in the ``README``.  Since you already ran ``sudo scons`` once you may need to start over with a clean checkout of CAMotics.  It may have written some files as ``root`` and running now with out ``sudo`` may fail.

**Comment by kigwaini** [comment]
Hi Joseph,

Thanks again for your continued support.

I added "sudo" because an earlier attempt had complained about write
permissions, but i guess that started a while back with checking out the
files using "sudo".

I will clean out everything and try again.

Now to learn how to clean botched installs 😞😞😞

**Comment by liushuya7** [comment]
I met the same problem. But it was solved by following the README running the command <ls $CBANG_HOME> again. Thanks!

**Comment by kigwaini** [comment]
Hi
Finally figuredfigured it out.
Followed the instructions...exactly.

On Feb 20, 2016 3:34 AM, "Josh" <notifications@github.com> wrote:
>
> I met the same problem. But it was solved by following the README running
the command again. Thanks!

**Comment by srakitnican** [comment]
Hello, is it necessary to do something special to make it search into standard distribution paths?

I've managed to build cbang, it is installing library into /usr/lib64/, and devel files into /usr/include/cbang/

**Comment by jcoffland** [comment]
It's not necessary to install cbang in the system folders.  You need to set ``CBANG_HOME``.  Make sure you follow the directions.
