### ISSUE TITLE
OpenSCAM didn't build in a foreign distribution

### ISSUE THREAD

**Issue by onekk** [CauldronDevelopmentLLC/CAMotics#112]
I'm compiling on Void Linux
but as i inspected your code it will be the same for arch or gentoo, I obtain this error:
 WARNING: Unrecognized POSIX distribution , trying to determine package type from filesystem

and OpenSCAM won't compile, I'm trying to package it for the distro I'm using so how to build it in a foreign distribution (not having dpkg or rpm on it)?

Regards

Carlo D.

**Comment by onekk** [comment]
Hi, I didn't figure out how to mend this issue, but i have switched my distro to debian and have installed flawlessy openscam on it.

Regards

Carlo D.

**Comment by jcoffland** [comment]
@onekk I think I've solved the problem with the above change.  If you've still got your Void Linux install around please confirm.

**Comment by onekk** [comment]
Unfortunately  I have substituted the Void Linux install with debian, so i can't reproduce the issue.

Many Thanks for your work, and your kindness, I'm starting the CNC Hobby, Hopefully a future job as I'm unemployed.

Best Regards
Carlo D.

**Comment by jcoffland** [comment]
Ok, thanks anyway.
