### ISSUE TITLE
Trouble selecting manual workpiece mode

### ISSUE THREAD

**Issue by mpohl727** [CauldronDevelopmentLLC/CAMotics#120]
Hello,

I've scoured the help sections.

Windows 8.1

-Importing gcode as a txt
-defining tools
-cannot select manual workpiece dimensions. (radio button will not stay selected)

The example files seem to work fine, as i can change the manual dimensions in there if i choose)

thank you,

Mike

**Comment by jcoffland** [comment]
Do you have example code where this fails to work?

**Comment by jcoffland** [comment]
Please reopen if you can provide more information.
