### ISSUE TITLE
No end of program code

### ISSUE THREAD

**Issue by DougCoffland** [CauldronDevelopmentLLC/CAMotics#121]
When loading programs that were created with TPL into linuxCNC, it complains of an invalid % code.  TPL puts this at the end of the program.  I have to edit the file to include a M2 ahead of the % code to get it to load without the error message.

Note, also that LinuxCNC complains that no % code is present if I take it out withoug putting in the M2.

For now, I'm working around this problem by putting in a print("M2"); statement at the end of the program

**Comment by jcoffland** [comment]
Fixed in 1.0.0 release.
