### ISSUE TITLE
Building from source fails if cbang is compiled wo/ libv8

### ISSUE THREAD

**Issue by karstengit** [CauldronDevelopmentLLC/CAMotics#130]
Please refer to https://github.com/CauldronDevelopmentLLC/OpenSCAM/issues/129

I tried to build OpemSCAM from source as described.
The first part with cbang works. I attached the result, compiled for AMD64.
![cbang tar xz](https://cloud.githubusercontent.com/assets/5941550/6943745/55af711c-d890-11e4-871e-a97d436f8a9e.png)

The compiling of OpenSCAM failed with many errors.
I attached the output.
![scons-errors log](https://cloud.githubusercontent.com/assets/5941550/6943789/8c37434a-d890-11e4-981c-14eb08636550.png)

**Comment by jcoffland** [comment]
It looks like you built C! with out libv8 but then installed it later.  You need to rebuild C!.  Unfortunately, once scons has detected that it cannot find libv8 it caches the result and continues to think the library is missing.  Perhaps the easiest way is to just do a full rebuild of C!.  Make sure the configuration phase for C! says, ```Checking for C library v8... (cached) yes``` with or with out the ```(cached)``` part.

You might also run in to problems with not having a new enough version of libv8.  Let me know how it goes.

**Comment by karstengit** [comment]
I am sorry - i never have to build C to compile something.
I would say i have only novice knowledge and i am learning ... ;-)

C needs to have a library included?

Today i will give up.
For the future i need a newer Linux distro to work with newer software.
That's the better solution of course.
But it would be fine when software works with actual stable distro's on the other hand ...

**Comment by jcoffland** [comment]
C! = cbang.  ```!``` can be read as "bang".

**Comment by karstengit** [comment]
The compiler must explode !?

**Comment by jcoffland** [comment]
Sometimes it does.

**Comment by karstengit** [comment]
Do i need a cleaning program afterwards? :-)
