### ISSUE TITLE
Can't Browse to Network Drives in Windows

### ISSUE THREAD

**Issue by ajayre** [CauldronDevelopmentLLC/CAMotics#139]
All my CNC files are on a network share, mapped as a drive in Windows. OpenSCAM doesn't display or let me choose anything but the C: drive. This is a fundamental problem.

**Comment by jcoffland** [comment]
In Windows, if I click on ```My Computer``` I can see other drivers.  Can you show me a screenshot of the problem?  Thanks for all the feedback.

**Comment by ajayre** [comment]
I've uninstalled the application so I can't make any screenshots, sorry. On my PC I have mapped network drives M: and P:. Going to My Computer in OpenSCAM only showed me C:. I am using Win7 64-bit.

**Comment by jcoffland** [comment]
Ok, I don't have a network drive to test this with.  There may be a limitation on which drives it can access.  I don't know why though.

**Comment by lome64** [comment]
Here's a screenshot of the problem.
Windows7 64bit CAMotics 1.0.6
![camotics_file_open](https://cloud.githubusercontent.com/assets/16515695/15568681/6e658730-232d-11e6-8b69-951ea23c94da.jpg)

**Comment by jcoffland** [comment]
As a workaround you should be able to type in ``\\server\path`` in to the location bar at the top.

**Comment by lome64** [comment]
>> As a workaround you should be able to type in \\server\path in to the location bar at the top.

Sorry. The path in that box cannot be edited. It's just a selection field.

  Lothar

**Comment by ajayre** [comment]
Entering obscure paths into boxes isn't very user-friendly. My advice would
be to only mark this as closed when a user-friendly solution has been
implemented. :)

**Comment by jcoffland** [comment]
Ah, I didn't realized I had closed the issue.  I believe I've fixed this in the source code.  It should be corrected in the next release.
