### ISSUE TITLE
Typing in workpiece numbers is oddly annoying

### ISSUE THREAD

**Issue by lordmundi** [CauldronDevelopmentLLC/CAMotics#149]
I can't tell what it is, but when I go to type in a number, let's say for a tool diameter, or for the dimensions of the workpiece, it is very annoying.  It looks like it is attempting to do something smart, but I can't really tell what it is.  If I type "1." I can then no longer type because it fills in the rest of the numbers for me up to some max precision.  And just highlighting some numbers and trying to type and replace them like one normally would leads to very odd behavior.  Almost every time I type, I look up and notice that what is in the field is not what I typed and I have to go correct digit by digit sometimes.

I'm running 0.2.5, so my apologies if this has already been fixed or if I'm just using it wrong.

**Comment by jcoffland** [comment]
Fixed in 1.0.0 release.
