### ISSUE TITLE
MasterCam X8 generated G-code not displayed

### ISSUE THREAD

**Issue by matswebjorn** [CauldronDevelopmentLLC/CAMotics#151]
I have a part which has been made in MasterCam X8, and from there generated G-code with Mach3 post-processor. But when I open the G-code file nothing is shown. I've tried other G-code simulators and they show the tool paths. Is there some way to upload the G-code so that someone can take a look?

**Comment by jcoffland** [comment]
As mentioned in the Google group the problem is that MasterCAM outputs a line ``O0000`` which is not valid LinuxCNC GCode.  The latest code ignores this rather than bombing out.
