### ISSUE TITLE
Camotics crashes during tool modification.

### ISSUE THREAD

**Issue by DougCoffland** [CauldronDevelopmentLLC/CAMotics#171]
Camotics closes without warning after the follow sequence of events:
1. Open Camotics.
2. Click "New Project"
3. Click "Tool View" tab
4. Any attempt to modify the tool, causes immediate closure of the Camotics and you have to start over.

**Comment by jcoffland** [comment]
I believe you are using an older version of CAMotics but I did find a possibly related bug in the latest version.

**Comment by jcoffland** [comment]
There is no "Tool View" tab in the latest code.  I think this is fixed.
