### ISSUE TITLE
LC_NUMERIC should always be overwritten to be "C"

### ISSUE THREAD

**Issue by koppi** [CauldronDevelopmentLLC/CAMotics#182]
Please remove ths if statement from the code:

https://github.com/CauldronDevelopmentLLC/CAMotics/blob/master/src/camotics/Application.cpp#L52

LC_NUMERIC should always be set to "C", IMHO.

See related issue: https://github.com/CauldronDevelopmentLLC/CAMotics/issues/100

**Comment by jcoffland** [comment]
Good point.
