### ISSUE TITLE
Import Stock and Tool definitions from G-code header

### ISSUE THREAD

**Issue by cmarhoover** [CauldronDevelopmentLLC/CAMotics#186]
Is it possible to import the definitions that MeshCAM writes into G-code headers when post-processing? This is intended for integration with the Cutviewer CNC simulation program, but perhaps it could also be useful for CAMotics? Here is an example of what these headers look like:

%
(FILENAME: /Users/hackintosh/Desktop/Circle.nc)
**(STOCK/BLOCK, 5.000, 5.000, 2.000, -0.000, -0.000, -0.000)**
G20
G90
**(TOOL/MILL,0.2500,0,1.0000,0.0)**
M6 T2
M3 S5000
G0X0.0000Y0.0000Z2.2500
(Parallel Rough)
(Roughing Level Depth: 1.875)
G0X2.5250Y2.5250
G1A0.0000Z1.8751F50.0
G1Z1.8751F300.0
X2.4750
…

**Comment by jcoffland** [comment]
This is already detailed in issue #71.  Closing this as a duplicate.
