### ISSUE TITLE
dxf.layer_cut can't find arc_angle()

### ISSUE THREAD

**Issue by DougCoffland** [CauldronDevelopmentLLC/CAMotics#187]
line 310 in dxf.tpl references the arc_angle method, but the interpreter fails to find the method.  I made it work by adding "this." in front of the reference to arc_anglt at line 310.

**Comment by jcoffland** [comment]
https://github.com/CauldronDevelopmentLLC/CAMotics/blob/master/tpl_lib/dxf/dxf.tpl#L310
