### ISSUE TITLE
File names with non-english characters fail

### ISSUE THREAD

**Issue by jcoffland** [CauldronDevelopmentLLC/CAMotics#190]

**Comment by CitizenOfDreams** [comment]
Clarification: when you try to add a G-code file with international characters in the name (Russian in my case), the file name in displayed incorrectly and the file contents shows empty. See attached screenshot.

![2016-08-28 12_47_02 annot](https://cloud.githubusercontent.com/assets/21288009/18032175/f32b2390-6d1e-11e6-9fb3-6c91153c5c7a.jpg)

**Comment by jcoffland** [comment]
Thanks, I'll look into it.

**Comment by CitizenOfDreams** [comment]
Sorry Jeff, but you closed the issue a bit prematurely. Files with Unicode names still don't work, at least for me.
- The file name is displayed correctly now;
- The file contents is displayed correctly;
- But the Simulation View tab stays empty.

**Comment by jcoffland** [comment]
Ok, so this was only partially fixed.  I going to open a new issue for the remaining item.
