### ISSUE TITLE
Qt 5 requires C++11 support, CXXFLAGS must be modified

### ISSUE THREAD

**Issue by christophe-vescovi** [CauldronDevelopmentLLC/CAMotics#193]
compilation terminate with error on Arch systems with the following error : "Qt requires C++11 support"
I manage to compile CAMotics by editing SConstruct file and adding the CXXFLAGS on this line
`if env['PLATFORM'] != 'win32': env.Append(CCFLAGS = ['-fPIC'],CXXFLAGS="-std=gnu++11")`
Do not know if it is a problem on other systems but because of this error the camotics package is broken in AUR (Arch User Repository).
Best regards,
Chris

**Comment by jcoffland** [comment]
The newest versions of Qt 5 have started requiring C++11 support.
