### ISSUE TITLE
Missing word in documentation

### ISSUE THREAD

**Issue by loldrup** [CauldronDevelopmentLLC/CAMotics#195]
> arc(x, y, z, angle, plane)
>  x, y and z specify the ????? from the current position to the far center of the helicial move in the selected plane. If the z value is zero then them move is a simple arc in the selected plane, otherwise it is a true helical move with an axis of length equal to the absolute value of the z value either above or below the selected plane through the current control point depending on the sign.
> 
> angle is the rotation of the arc in radians. A positive value indicates a clockwise rotation, negative a counter-clockwise rotation.
> 
> plane specifies to which plane the helical axis is perpendicular. Valid values are XY (the default), XZ or YZ.

**Comment by jcoffland** [comment]
The missing word is ``offset``.  It's fixed now.  Thanks.
