### ISSUE TITLE
Drop Qt4 support?

### ISSUE THREAD

**Issue by martonmiklos** [CauldronDevelopmentLLC/CAMotics#202]
Hi Joseph,

I have recently seen that my last PR got stuck a travis build check because it build with Qt4 qhile I used Qt5 for the development. 

What is the game plan with Qt4? Are you planning to obsolete the support or not? If yes in what timeframe? I am asking it because if the support will stay I will refactor my patch to support Qt4 too.

**Comment by jcoffland** [comment]
I would like to retain Qt4 support for now.

**Comment by martonmiklos** [comment]
Roger that!
