### ISSUE TITLE
 error: 'class cb::CommandLine' has no member named 'setShowKeywordOpts'

### ISSUE THREAD

**Issue by midyukov-anton** [CauldronDevelopmentLLC/CAMotics#204]
Does not work build the version 1.0.6. ALT Linux, x86-64 gcc6 or gcc5, cbang 1.0.1

g++ -o build/build_info.o -c -std=gnu++98 -O3 -funroll-loops -ffast-math -mfpmath=sse -fno-unsafe-math-optimizations -msse2 -fPIC -DNDEBUG -D_REENTRANT -DHAVE_EXPAT -DHAVE_PTHREADS -DHAVE_LIBSQLITE -DHAVE_OPENSSL -DHAVE_CBANG -DUSING_CBANG -DGLEW_STATIC -DQT_CORE_LIB -DQT_GUI_LIB -DQT_OPENGL_LIB -DQT_SHARED -I/usr/src/RPM/BUILD/cbang-1.0.1/src -I/usr/src/RPM/BUILD/cbang-1.0.1/include -I/usr/include/qt4 -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtOpenGL -I/usr/include/freetype2 -I/usr/include/libpng15 -Isrc -Ibuild build/build_info.cpp
build/camotics/Application.cpp: In constructor 'CAMotics::Application::Application(const string&)':
build/camotics/Application.cpp:70:11: error: 'class cb::CommandLine' has no member named 'setShowKeywordOpts'
   cmdLine.setShowKeywordOpts(false);

**Comment by jcoffland** [comment]
But [it does](https://github.com/CauldronDevelopmentLLC/cbang/blob/master/src/cbang/config/CommandLine.h#L80).  You need to update and rebuild cbang first.
