### ISSUE TITLE
Indicate axes positive direction in GUI

### ISSUE THREAD

**Issue by greyltc** [CauldronDevelopmentLLC/CAMotics#206]
The rendering of the axes indicator in the simulation view is not clear on which direction is positive.
![screenshot from 2017-01-27 13-30-25](https://cloud.githubusercontent.com/assets/16778174/22372484/e75dc066-e494-11e6-85a0-7cfafa13ee6a.png)

**Comment by jcoffland** [comment]
How should this be done?  Could maybe float a plus sign near the positive side.

**Comment by greyltc** [comment]
I'd just delete the arrows that point along negative directions. That should remove any ambiguity.
Here are some examples from freecad's axis/origin indicators:
![screenshot from 2017-01-30 10-31-40](https://cloud.githubusercontent.com/assets/16778174/22419926/9e16e8e8-e6d7-11e6-86a1-04464310d7bc.png)
![screenshot from 2017-01-30 10-31-24](https://cloud.githubusercontent.com/assets/16778174/22419929/a16ff53e-e6d7-11e6-8e9f-8d0b479e944b.png)
