### ISSUE TITLE
CAMotics does not show up under "Open With" dialog under Gnome

### ISSUE THREAD

**Issue by srakitnican** [CauldronDevelopmentLLC/CAMotics#213]
So CAMotics does not show up under "Open With" dialog under Gnome DE, possibly even other environments. The reason for that is that there is no %f or %F specified in CAMotics.desktop, "Exec=" key.

https://standards.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html#exec-variables

**Comment by jcoffland** [comment]
File updated.  Thanks.

**Comment by jcoffland** [comment]
Fixed in upcoming v1.2.0 release.
