### ISSUE TITLE
TPL print() doesn't send output to G-code stream?

### ISSUE THREAD

**Issue by sheffieldnick** [CauldronDevelopmentLLC/CAMotics#224]
The documentation for [TPL print()](http://tplang.org/#print) says "_writes to the same output stream as the gcode functions so if you don't want to interfere with the gcode output you should wrap text in parentheses_".

However any print() statements I try get written to the console instead, and ignored by the CAMotics G-code interpreter. Nor are they included when I do File->Export Gcode.

**Comment by jcoffland** [comment]
Fixed in upcoming release v1.2.0.
