### ISSUE TITLE
Qt cannot find "windows" plugin on Windows

### ISSUE THREAD

**Issue by LETARTARE** [CauldronDevelopmentLLC/CAMotics#228]
Hello,
launching camotics it does not find the plugin 'qwindows.dll'
![camotics_error](https://cloud.githubusercontent.com/assets/5158475/25129871/324263e4-2440-11e7-9ac2-bae3c84d33d8.png).
I use Vista Business Pack2.
The directory 'platforms' exists with '' qwindows.dll.

This defect appears from Qt5.6 (not with camotics-1.06, qt4)
Thanks for this excellent work.

**Comment by LETARTARE** [comment]
Hello,
would you have a track to fix it ?
Have a good day

**Comment by jcoffland** [comment]
Seems to be fixed in upcoming v1.2.0 release.
