### ISSUE TITLE
api-ms-win-crt-runtime-l1-1-0.dll is missing with Windows 7 or Vista

### ISSUE THREAD

**Issue by Bmaxwe47** [CauldronDevelopmentLLC/CAMotics#229]
I am receiving the following error and followed instruction and redownloaded - still same error

```
api-ms-win-crt-runtime-l1-1-0.dll is missing
```

what do I need to do?  reinstall didn't work

**Comment by jcoffland** [comment]
Ths is a problem on Windows 7 and Vista with CAMotics v1.1.1 and newer.  It should be fixed by installing this Windows update: https://support.microsoft.com/en-us/help/2999226/update-for-universal-c-runtime-in-windows

**Comment by jcoffland** [comment]
Should be fixed in the new v1.2.0 release.
