### ISSUE TITLE
Building CAMotics with custom flags

### ISSUE THREAD

**Issue by ksuprynowicz** [CauldronDevelopmentLLC/CAMotics#230]
Hi!
I tried to build CAMotics with custom CXXFLAGS="-march=native -ftree-vectorize", and they seem to be ignored. Is there a way to apply them so they will get passed to g++?

**Comment by jcoffland** [comment]
Try this:

    scons ccflags="-march=native -ftree-vectorize"

Let me know if you get any significant speed up.
