### ISSUE TITLE
SConstruct Qt5 pkgconfig

### ISSUE THREAD

**Issue by srakitnican** [CauldronDevelopmentLLC/CAMotics#242]
Not quiet sure what is SConstruct doing with the pkgconfig modules, but they seems to be named differently from Qt4 modules.

https://github.com/CauldronDevelopmentLLC/CAMotics/blob/master/SConstruct#L88

QtCore -> Qt5Core
QtGui -> Qt5Gui
QtOpenGL -> Qt5OpenGL
QtNetwork -> Qt5Network
QtWidgets -> Qt5Widgets
QtWebSockets -> Qt5WebSockets

At least that is how it is on Fedora 25.

**Comment by srakitnican** [comment]
Ok, it seems to correct the names here:
https://github.com/CauldronDevelopmentLLC/CAMotics/blob/master/config/qt5/__init__.py#L929

**Comment by jcoffland** [comment]
Right, those are qt4 compatible names.
