### ISSUE TITLE
CATCH_WARNING() and throws function related error 

### ISSUE THREAD

**Issue by badrik91** [CauldronDevelopmentLLC/CAMotics#245]
i have a doubt in catch_warning and throws function. In this, i got error like invalid operands of types ``‘const char [11]’ and ‘std::vector<std::__cxx11::basic_string<char> >::size_type {aka long unsigned int}’ to binary ‘operator<<’ this and expected primary-expression before ‘)’ token.``
please give solution i am in new for this project.

**Comment by jcoffland** [comment]
You need to provide a lot more information here.  Please tell us your OS, the version you installed, or code you're building, what instructions you're following and the exact error including line numbers.  Otherwise, it's nearly impossible to diagnose the problem you've encountered.

**Comment by badrik91** [comment]
I am using ubuntu 16.04 OS,QT 5.9 and i follow this  link https://github.com/CauldronDevelopmentLLC/CAMotics and build in linux ,follow the instuction for linux.I installed all dependency which is given in instructionThis is the exactly error .
![screenshot from 2017-08-11 09-36-36](https://user-images.githubusercontent.com/15092386/29201075-ab67a3be-7e78-11e7-8a60-9569332f155f.png)
please give answer.
 thanks for your reply .

**Comment by badrik91** [comment]
I have define this kind of macro then like this,
![2](https://user-images.githubusercontent.com/15092386/29201243-277fd89e-7e7a-11e7-9219-d3a1232075ad.png) is it right or wrong?
then get this kind of error like,
![3](https://user-images.githubusercontent.com/15092386/29201256-4640b690-7e7a-11e7-9264-3470bafd7ba3.png)

**Comment by jcoffland** [comment]
You cannot build CAMotics from Qt creator.  The instructions tell you how to do it from the command line using ``scons``.  See: http://camotics.org/download.html#source-code or https://github.com/CauldronDevelopmentLLC/CAMotics#building-from-source

**Comment by badrik91** [comment]
Thank you sir for giving reply.
But I did this using commandline also but it simply run this in terminal.
but i want to build this in framework like Qt,Visual studio.but you said
not to build in Qt then where I build this project?
Please give solutions.

On 13-Aug-2017 12:31 AM, "Joseph Coffland" <notifications@github.com> wrote:

Closed #245 <https://github.com/CauldronDevelopmentLLC/CAMotics/issues/245>.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/CauldronDevelopmentLLC/CAMotics/issues/245#event-1203695052>,
or mute the thread

**Comment by jcoffland** [comment]
You have to build it on the command line using ``scons``.  Follow the instructions I linked above.  If you encounter an error then paste it here.

**Comment by badrik91** [comment]
Hello Sir,
I followed the link you have given but it create direct exe but i want to
modify the code for my requirement.so how i get successfully compiled ?
please give solution .

**Comment by jcoffland** [comment]
If you want to build from source you must follow the directions I linked to above.

**Comment by badrik91** [comment]
Hello Sir,
I have a problem in  related scon which is given bellow
![screenshot from 2017-08-17 12-02-44](https://user-images.githubusercontent.com/15092386/29398835-7c6342a0-8344-11e7-86fe-d0cab9c20e08.png)
please give solution .
I followed all the steps which you are given .

**Comment by jcoffland** [comment]
Remove the directory ``/home/spr/CAMotics/camotics``.  It is preventing the build from working.

**Comment by badrik91** [comment]
How can i remove this?because i have installed source code in /home/spr/CAMotics.so what can i do?
please give solution

**Comment by jcoffland** [comment]
My recommendation is to delete everything in your ``/home/spr/CAMotics`` directory and start over.  If you follow the [directions](https://github.com/CauldronDevelopmentLLC/CAMotics#building-from-source) **precisely**, it does work.  Many other people have compiled CAMotics successfully.

**Comment by badrik91** [comment]
Thank you sir.
