### ISSUE TITLE
ChakraCore builds under Windows 10 but dynamic linking fails

### ISSUE THREAD

**Issue by jcoffland** [CauldronDevelopmentLLC/CAMotics#248]
Oddly CAMotics builds and runs fine with ChakraCore in Linux but on Windows the run-time fails.  There are errors when the ChakraCore API is accessed.  Presumably, it's unable to load the DLL and access the API functions.  I'm not an expert at building software for Windows by any means so we have abandoned ChakraCore support in favor of libv8 for now.

Relevant code:
 * https://github.com/CauldronDevelopmentLLC/cbang/tree/master/src/cbang/chakra Chakra module
 * https://github.com/CauldronDevelopmentLLC/cbang/tree/master/src/cbang/js Implementation independent wrapper
 * https://github.com/CauldronDevelopmentLLC/cbang/tree/master/src/cbang/v8 V8 module

The build system is [scons](http://scons.org/).  Instructions for building CAMotics on Windows can be found here: https://github.com/CauldronDevelopmentLLC/CAMotics/blob/master/doc/Windows_Build.md  Cbang can be built against ChakraCore, V8 or both by setting ``CHAKRA_CORE_HOME`` or ``V8_HOME`` environment variables to the source directory.

**Comment by xiaozhaolook** [comment]
that's really a pity, I am considering to learn some technology and skill for simulate 3D print path solution, can you give me some advices? thanks in advance!

**Comment by jcoffland** [comment]
@xiaozhaolook  you don't need ChakraCore to run CAMotics in Windows.  It works with Google's v8 Javascript engine.

**Comment by jcoffland** [comment]
Not using ChakraCore any more.
