### ISSUE TITLE
wrong display of the plunges

### ISSUE THREAD

**Issue by jkmnt** [CauldronDevelopmentLLC/CAMotics#250]
The plunges (maybe with X/Y movement ?) are displayed wrong in 1.1.+ versions. It is very evident on the holding tabs, please see below:

v1.1.1:
![wrong_plunge](https://user-images.githubusercontent.com/16407084/30139593-823f3416-9377-11e7-881d-73aeb39795d6.png)

v1.0.5:
![right_plunge](https://user-images.githubusercontent.com/16407084/30139598-888c2b94-9377-11e7-9b30-e3fc819cdcfa.png)

used nc code & xml project:
[wrong_plunge_nc.zip](https://github.com/CauldronDevelopmentLLC/CAMotics/files/1283024/wrong_plunge_nc.zip)

**Comment by jcoffland** [comment]
Thanks for the nice clean example.  I wish everyone did it like this. You are absolutely right.  I already found and fixed this bug.  The next release, which I hope to get out soon, fixes this problem.

I'm currently tied up with our Kickstarter campaign.  http://buildbotics.com/kickstarter

**Comment by jkmnt** [comment]
Ok, thanks. Good luck with the campaign !

**Comment by jcoffland** [comment]
Fixed in upcoming v1.2.0 release.
