### ISSUE TITLE
CAMotics 1.1.1 does not run on Windows XP.

### ISSUE THREAD

**Issue by lome64** [CauldronDevelopmentLLC/CAMotics#252]
After installing the 1.1.1 Windows 32bit version, "camotics.exe is not a valid 32bit application" pops up.

**Comment by jcoffland** [comment]
What version of Windows are you using?  I just tried CAMotics 1.1.1 on 32-bit Windows 10 and it worked correctly.

**Comment by lome64** [comment]
I must admit it's an older machine with the last version of Windows XP on it.
We keep it running in order to use attached hardware which has no drivers for more recent versions of Windows.
The version 1.0.6 (1.0.4?) however of Camotics worked fine on that machine.
Stictly it's not necessary to run Camotics on that old machine, but I noticed the problem and wanted to let you know.
Lothar

**Comment by jcoffland** [comment]
Thanks for letting me know.  CAMotics 1.1.1 does not work on XP.  The next release will make this clear at install time.
