### ISSUE TITLE
Black screen in v1.1.1

### ISSUE THREAD

**Issue by mariana-oliveiraa** [CauldronDevelopmentLLC/CAMotics#260]
Hello,

My installation of camotics v1.1.1 on linux mint do not show any simulation, only a black screen otherwise the program is responsive.

Earlier versions such as v1.0.x work but exhibit strange tool paths as we can see on the picture attached.

Any ideias?
Many thanks,
Mariana

![screenshot at 2018-04-04 15-36-38](https://user-images.githubusercontent.com/22432941/38314424-ad184e1e-3815-11e8-895e-1617e2604c4e.png)

**Comment by jcoffland** [comment]
The jagged lines are due to a problem parsing numbers in a locale that uses commas as the decimal separator.  This was fixed in later versions of CAMotics.  See #180.  You can work around this by running CAMotics like this: ``LC_NUMERIC=C camotics``.

I'm not sure why you are seeing a black screen on v1.1.1.  Try running CAMotics in a terminal and look for error codes.  If you find any errors please post them here.

**Comment by mariana-oliveiraa** [comment]
Hi,

Your advice worked, thank you!

I run CAMotics v1.1.1 in a terminal and does not have any error...
I'm using Linux Mint 18.1.

Many thanks
Mariana

**Comment by sns5400** [comment]
Hello, after install camotics on my Linux Mint 18.3 like the description i have the same problem, no screen at all. When start in terminal it give error:

pierre@pierre-X58A-UD7 ~ $ camotics
camotics: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
pierre@pierre-X58A-UD7 ~ $

**Comment by jcoffland** [comment]
@sns5400 sorry, that's not the same issue discussed here.  You need to install ``libssl`` version 1.1.x

**Comment by sns5400** [comment]
How can i do that. Why the installation do not fix this ?

**Comment by jcoffland** [comment]
If you are on a Debian based Linux system you can try this:
```
sudo apt-get install -y libssl1.1
```

**Comment by sns5400** [comment]
Thank you for the quick reaction but still have a problem
I am not a linux specialist but try to work with it, in attachment i
include my terminal screen.
Maybe i can add a repository but how i now where i can find this libssl
?
Anyway thank you forr help
gr
