### ISSUE TITLE
Add V-shape tool

### ISSUE THREAD

**Issue by lucky62** [CauldronDevelopmentLLC/CAMotics#261]
Please add new type of tool - V-shape (V-nose) like this:
![image](https://user-images.githubusercontent.com/16965519/40283387-9b8dd592-5c7d-11e8-8381-4f824fc839e2.png)

**Comment by jcoffland** [comment]
V-shaped tools already exist.  It's called a conical tool in CAMotics.  What is not yet supported is composite tools.  To correctly simulate the tool pictured above you would need a composite tool consisting of a cylindrical tool combined with a conical tool.  There is already an open issue for composite tools.  See #45.
