### ISSUE TITLE
Can't create new TPL or gcode file on Windows 10

### ISSUE THREAD

**Issue by DougCoffland** [CauldronDevelopmentLLC/CAMotics#266]
I am not able to create a new tpl or gcode file from CAMotics when running Windows 10. I installed the AMD 64-bit version from the CAMotics.org web site. Installation went fine.

After creating a new project with IMPERIAL units with an empty tool table, I added a tool. Then I attempted to create a tpl file by right-clicking in the files box on the left and selecting "add file". After selecting, tpl or gcode, it takes me to a directory with the file name defaulting to the same name as the project, but with the appropriate extension already loaded into the extension field. When I click Open, I get an error message that says "file not found".

This sequence works correctly on Debian. I noticed this on Matt Dralle's computer and then duplicated the problem on my own computer.

There does not seem to be a way to create a new tpl or gcode file from within CAMotics on Windows 10. The work around is to create an empty text file with the .tpl or .ngc extension outside of CAMotics and then open it from within CAMotics.

**Comment by jcoffland** [comment]
Fixed in v1.2.0.
