### ISSUE TITLE
Can't run a tpl program from CAMotics on Windows 10

### ISSUE THREAD

**Issue by DougCoffland** [CauldronDevelopmentLLC/CAMotics#267]
I am running the AMD-64 bit version of CAMotics on Windows 10.

When I try to run the simplest of programs, I get the following errors:
"Errors were encountered during tool path generation. See console output for more details."

The the console says:
Error:Exception: @9:24 Unexpected end of expression.

The contents of the tpl file are:
_______
  units(METRIC);
  rapid({z: 5});
______
I can run the same command from tplang.exe directly from the command line with no problems.

**Comment by jcoffland** [comment]
I believe this was caused by the filename having the wrong extension.
