### ISSUE TITLE
CAMotics does not run on Mac

### ISSUE THREAD

**Issue by DougCoffland** [CauldronDevelopmentLLC/CAMotics#269]
CAMotics default code does not simulate on Mac. Also, cannot create new tpl program from within CAMotics. And, cannot generate GCode from within CAMotics on Mac.

**Comment by pvgennip** [comment]
I have the same problem reloading the camotics.tpl example file (that should load the DXF layer 0), however, the output window said: 
dyld: Library not loaded: QtOpenGL.framework/Versions/4/QtOpenGL
  Referenced from: /Applications/CAMotics.app/Contents/MacOS/tplang
  Reason: image not found

**Comment by jcoffland** [comment]
This is a duplicate of #209.
