### ISSUE TITLE
GCode editor screen not updating correctly

### ISSUE THREAD

**Issue by jcoffland** [CauldronDevelopmentLLC/CAMotics#300]
Calin Anca wrote:

I am having some trouble trying to edit Gcode in the program console.  Basically what happens is, when I try to add code, edit code I can't even see the cursor unless I click on the simulation view tab and then go back to the project tab. I can, for example, use the backspace key to delete some lines in the code or add some new line and write code but it won't show up unless I click on the simulation view tab and then go back to the project. Hope you can help. I have attached a [video](https://github.com/CauldronDevelopmentLLC/CAMotics/files/3004791/video.zip) with a recording of my screen while using the program so you can see what I mean.

My laptop runs Windows 10 home its an Intel Core i5 5300HQ 8GB RAM Nvidia GTX 950M.

**Comment by jcoffland** [comment]
It looks like the GCode tab is just not updating correctly.

I was not able to reproduce this problem so I'm not sure how to fix it.  Do you have the latest driver for your NVidia GPU installed?

**Comment by Zeannn** [comment]
This is happening to me on the latest version. I’m running on Windows 11 with Nvidia GPU. Anyone knows the fix to this?
