### ISSUE TITLE
"Failed to load OpenGL" when QT_OPENGL=angle is set. [SOLVED]

### ISSUE THREAD

**Issue by mjknoll** [CauldronDevelopmentLLC/CAMotics#301]
So I read the 2 other issues with opengl and I am receiving a similar error but I am using a 1060 with the newest Nvidia driver and still getting an error about opengl 2.0. I also got the opengl extentions viewer tool and see that it shows 3.0+.  Must be something 2.0 specific it needs?

![image](https://user-images.githubusercontent.com/33679610/55293163-05a0f300-53b9-11e9-93b1-d93d707f196c.png)

![image](https://user-images.githubusercontent.com/33679610/55293232-e22a7800-53b9-11e9-87eb-c153968e86f9.png)

**Comment by jcoffland** [comment]
It's likely CAMotics is finding another ``opengl.dll`` file somewhere on your system that does not support 2.0.  Do a search for ``opengl.dll`` to see how many of them can be found.

**Comment by mjknoll** [comment]
Nothing but these.
![image](https://user-images.githubusercontent.com/33679610/55293675-7bf42400-53be-11e9-93af-7fe105b745d6.png)

**Comment by jcoffland** [comment]
You could try running CAMotics under http://dependencywalker.com/ to see which dlls it's actually loading.

**Comment by mjknoll** [comment]
Not very familiar with that software but the only reference to opengl I am finding after loading and profiling is this.

versionFunctions: Not supported on OpenGL ES

**Comment by jcoffland** [comment]
Does it work if you set the environment variable ``QT_OPENGL=desktop``?

**Comment by mjknoll** [comment]
Yes it runs with it set to desktop, was set to angle.

**Comment by jcoffland** [comment]
If I understand you correctly, ``QT_OPENGL=angle`` was already set on your system?

**Comment by mjknoll** [comment]
Yes it was set to angle that seems to break camotics. I can put anything else in there, even invalid arguments and it will run fine. I am assuming it was set by another piece of software that is using qt opengl.

**Comment by jcoffland** [comment]
Yes, I think you are right.  ``QT_OPENGL=angle`` tells Qt to use OpenGL ES2.0 for everything.  CAMotics is not yet compatible with OpenGL ES2.0.  However, I plan to convert it to ES2.0.
