### ISSUE TITLE
Automatic line numbering

### ISSUE THREAD

**Issue by Foadsf** [CauldronDevelopmentLLC/CAMotics#303]
As I have mentioned [here ](https://www.reddit.com/r/CNC/comments/b9abr8/free_gcode_editors_with_automatic_line_numbering/) I'm looking for a G-code editor with automatic line numbering, because that's one of the most difficult things to do manually. CAMotics seems like a natual environment to ask for it because it seems to be the most viable Free, Libre, Open Source Software for CAM/CNC simulation out there. 

**P.S.** see a list of other Free CNC/CAM software [here](https://www.reddit.com/r/CNC/comments/aizatc/free_and_open_source_camcnc_software/).

**Comment by jcoffland** [comment]
If you export GCode in CAMotics it is automatically numbered.  You can also use the command line tool ``gcodetool``.
