### ISSUE TITLE
camotics_1.2.0_amd64.deb doesn't require libQt5WebSockets

### ISSUE THREAD

**Issue by dismine** [CauldronDevelopmentLLC/CAMotics#304]
I successfully installed CAMotics 1.2 on Ubuntu 18.04.2, but when i try to run it i get:
`camotics: error while loading shared libraries: libQt5WebSockets.so.5: cannot open shared object file: No such file or directory`

Installing the library helped.

**Comment by jcoffland** [comment]
Got it.  Thanks!
