### ISSUE TITLE
Conical shape does not support common V bit

### ISSUE THREAD

**Issue by minimum99** [CauldronDevelopmentLLC/CAMotics#314]
A typical V-bit, as shown below, has cutting surfaces extended beyond the V 
shape. If Conical shape in Camotics is chosen to represent this tool, the 3D simulation does not accurately render the result. Can we add support for this type of V-Bit, which is commonly used in V carving?

![conical](https://user-images.githubusercontent.com/42755940/67623010-0a097f00-f7d5-11e9-84cf-838c34ca08d2.jpg)

**Comment by jcoffland** [comment]
This is a known issue and is documented in #45.  The tool above could be compsed of a cyilder and a cone.  It's on the list of things to do.  I'm closing this as a duplicate.
