### ISSUE TITLE
Cannot click manual workpiece radio button

### ISSUE THREAD

**Issue by curnowdj266** [CauldronDevelopmentLLC/CAMotics#319]
Hello,
I am just learning CAMotics and I don't seem to be able to select the manual workpiece radio button when starting a new project. Is there something I am missing? This is on Ubuntu Linux 18.04 LTS
TIA

**Comment by jcoffland** [comment]
You should be able to just click it.  It's useful to first load some GCode or TPL so you have a path to work with.  CAMotics will then calculate a default workpiece.  Upload a screenshot if you still have a problem.
