### ISSUE TITLE
Failed to build on windows10 platform

### ISSUE THREAD

**Issue by NateChen733** [CauldronDevelopmentLLC/CAMotics#324]
Hello Sir,
I want to build CAMotics on the window10 platform. I follow the steps listed in the file Windows_Build.md, but there is an error, the Options is not defined, how can I solve it? Thank you.

![sshot-2020-04-19- 1](https://user-images.githubusercontent.com/63957141/79687449-e43bcf00-8279-11ea-92cf-a74bb7acf725.png)

**Comment by jcoffland** [comment]
This is a ``v8`` build error.  You may need a different version of ``scons``.  I'm sorry, don't know what that is.  Building ``v8`` on Windows is beyond the scope of this project.

**Comment by NateChen733** [comment]
Okay, thanks for your help.
