### ISSUE TITLE
Can I Integrate CAMotics into my Qt5 application?

### ISSUE THREAD

**Issue by LevZer01** [CauldronDevelopmentLLC/CAMotics#330]
Hello,
Is it possible to integrate  CAMotics  to my Qt/c++ application ?  
I am developping a HMI application, i want to simulate the cnc tool path inside my application. 
Does someone know if it is possible and if yes, where/how should i start please ?
Thank you in advance
Lev

**Comment by jcoffland** [comment]
Yes, if your software is Open-Sourced under the GPL license v2 or later.  Otherwise, no, it would be a violation of the license agreement.

**Comment by luzpaz** [comment]
It's being done with FreeCAD, see https://github.com/FreeCAD/FreeCAD/pull/4672

Ticket could be closed.
