### ISSUE TITLE
XYZ Digital Display

### ISSUE THREAD

**Issue by 1Metalguru** [CauldronDevelopmentLLC/CAMotics#333]
This is not a bug, just a suggestion for a feature.

It would be extremely useful to have an XYZ position display to show the real time axis position values during simulation.

This would make it much better for troubleshooting  to compare commanded position with actual.

Metalguru

**Comment by jcoffland** [comment]
This functionality has existed since the beginning.  It's in one of the docks.

**Comment by 1Metalguru** [comment]
Wow.  That only took 3 years to reply to...
