### ISSUE TITLE
Lag and computer getting hang

### ISSUE THREAD

**Issue by HiyaGada** [CauldronDevelopmentLLC/CAMotics#343]
I've been facing a lot of lag after running the GCode in CAMotics. Usually, this happens when I run codes that have a lot of arcs. Is there a solution for this? I have an exam in a week :(

**Comment by jcoffland** [comment]
If you're running big simulations it can use up all your system memory.  This can cause your operating system to push things out of memory and on to disk.  It will then have to reload those things from disk later thus causing the computer to lag.  This is not specific to CAMotics.  Just don't run large simulations and it will go away.
