### ISSUE TITLE
SCons build fails on scons 4.1.0

### ISSUE THREAD

**Issue by dpreed** [CauldronDevelopmentLLC/CAMotics#344]
Using the current scons, the config/qt5/__init__.py file has an error in line 50

`./config/qt5/__init__.py:class ToolQt5Warning(SCons.Warnings.Warning): pass`
fails because Warning is not defined anymore. Instead it has been renamed to SConsWarning, so that line should be edited to
`./config/qt5/__init__.py:class ToolQt5Warning(SCons.Warnings.SConsWarning): pass`

Then the build succeeds.

**Comment by jcoffland** [comment]
I belive the above commit fixes this problem.  Reopen if not.
