### ISSUE TITLE
Save Simulated carved object to file.

### ISSUE THREAD

**Issue by casiobearing** [CauldronDevelopmentLLC/CAMotics#350]
If the simulated carved object could be saved as a STL file or similar, it would be possible to import it back into e.g. Solidworks where you could do measurement analysis on it to double check cut widths etc.

**Comment by jcoffland** [comment]
You're in luck.  This is already possible.  After your simulation is complete, go to ``Tools`` -> ``Export``.  Then select ``Surface`` then click ``OK``.
