### ISSUE TITLE
Is there an installation package for version 1.2.2 of window10?

### ISSUE THREAD

**Issue by maxwang531** [CauldronDevelopmentLLC/CAMotics#353]
As the title indicates, I found that the latest version should be 1.2.2, but this only provides a compressed package for download. After downloading, I am not very sure how to build the software from the files in this compressed package. Can anyone provide Some help?

Another question is whether CAMotics provides a headless operation mode, similar to using python program control software in Pycharm?

**Comment by Qvinto1** [comment]
Yes can we please have compiled version of the release candidates for Windows and Mac

**Comment by jcoffland** [comment]
1.2.2 will not be released.  I'm working on 1.3.0 but need some beta testers.
