### ISSUE TITLE
Chocolatey package for Windows

### ISSUE THREAD

**Issue by Foadsf** [CauldronDevelopmentLLC/CAMotics#361]
It would be great if you could add the software to the Chocolatey package manager as requested [here](https://github.com/chocolatey-community/chocolatey-package-requests/issues/1295).

**Comment by luzpaz** [comment]
A downstream chocolatey package exists:

[![Chocolatey package](https://repology.org/badge/version-for-repo/chocolatey/camotics.svg)](https://repology.org/project/camotics/versions)

This issue can be closed
