### ISSUE TITLE
improving the documentation - where can I find EXPLAINED example gcode-files

### ISSUE THREAD

**Issue by StefanL38** [CauldronDevelopmentLLC/CAMotics#379]
Hi everybody,

This issue is about improving the documentation.

I'm using ESTLCAM for CAD-CAM. And I'm familiar with the GCode in general.
But I haven't found any information about how to properly make camotics accept different tools.

Of course I have looked up the example *.nc-files 
but the pure GCode does not explain what kind of commands camotic expects to change a tool.

Of course I have read the usermanual here
https://camotics.org/manual.html
but there are no details about my question

So if there is somewhere information about this the online usermanual should have a link to it
or if this information does not yet exists it should be written.
If somebody explains it to me I'm willing to add this to the documentation.

best regards Stefan

**Comment by jcoffland** [comment]
The GCode accepted by CAMotics is documented here: https://camotics.org/gcode.html  There are many resources on the Internet which explain how to create GCode.  Explaining CNC programming concepts is outside the scope of CAMotics.
