### ISSUE TITLE
Custom Tool Shape

### ISSUE THREAD

**Issue by sananToplic** [CauldronDevelopmentLLC/CAMotics#388]
Hi there i would be nice when it where possible to add custom tool shapes i.e. for Profile as dxf or svg.
In Woodworking we have many Profiles for Milling i use Estlcam to generate the toolpath and camotics to visualise. Since i found the Software i love it. Thanks for this beauty peace of Software.

**Comment by jcoffland** [comment]
The algorithm CAMotics uses does not support arbitrary shapes.  There's already an issue open for composite tool shapes #45 as well as some other shapes #232.
