### ISSUE TITLE
All dialog boxes broken

### ISSUE THREAD

**Issue by rob-deutsch** [CauldronDevelopmentLLC/CAMotics#391]
Hi there, it seems like all dialog boxes are broken in my compile of CAMotics from the `master` branch.

The problem is that clicks and changes in the dialog boxes don't actually make anything change. 

For example you can see thisin two places:

1. Open the Tool Editor, change the Shape, and observe that nothing in the dialog box changes, so you can't enter the right parameters for that particular shape.

2. Open settings, change the resolution dropdown box, and notice that the number doesn't change. Also, enabling the planner doesn't enable all of the configuration options for the planner.

It seems like commit bd9c754418dfdc3f6dfd137b08c8477106b9a112 is where its broken. The commit just beforehand works fine.

I suspect this has to do with changing all of the dialog boxes to subclass from `Dialog` instead of from `QDialog`, but I don't know enough about QT to fix this.

**Comment by jcoffland** [comment]
I believe this is fixed by the above commit.  Thanks for the report!

**Comment by rob-deutsch** [comment]
Seems to work for me, thanks!
