### ISSUE TITLE
scons: *** No tool module 'config' found in /home/xyz/src/cbang/tools, /usr/lib/python3/dist-packages/SCons/Tool

### ISSUE THREAD

**Issue by gcanzalo** [CauldronDevelopmentLLC/CAMotics#396]
I've followed the instructions to the letter. Several times. cbang builds w/o error.

Linux xyz 6.1.0-9-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.27-1 (2023-05-08) x86_64 GNU/Linux

**Comment by jcoffland** [comment]
Most likely you don't have ``CBANG_HOME`` set correctly.

**Comment by gcanzalo** [comment]
I followed your directions; your response is very much like them, so I'll withdraw both my issue and my plans to use your software.
