### ISSUE TITLE
Error when building: No such file or directory AsyncCopyStreamToLog.h

### ISSUE THREAD

**Issue by bluesun212** [CauldronDevelopmentLLC/CAMotics#413]
When running scons to compile CAMotics, the following error was observed:
```
src/camotics/sim/ToolPathTask.cpp:48:10: fatal error: cbang/log/AsyncCopyStreamToLog.h: No such file or directory
   48 | #include <cbang/log/AsyncCopyStreamToLog.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
scons: *** [build/camotics/sim/ToolPathTask.o] Error 1
scons: building terminated because of errors.
```
This seems to have started after a [recent commit in cbang where AsyncCopyStreamToLog.h was deleted](https://github.com/CauldronDevelopmentLLC/cbang/commit/149f3945d345362a38b300edae46a10489d196a6).  It doesn't appear that `ToolPathTask` needs to import this file; removing the include line in question allowed the build to succeed.

**Comment by jcoffland** [comment]
Thanks
