### ISSUE TITLE
Conical tools have flat tips

### ISSUE THREAD

**Issue by pstemari** [CauldronDevelopmentLLC/CAMotics#421]
Sometimes round, but usually flat.  The difference is really important when doing fine variable-depth engraving (v-engraving).  The diameter of the tip directly adds to the width of any lines engraved.

See https://github.com/pstemari/v-engrave-plugin for some examples.

**Comment by jcoffland** [comment]
Conical tools with flat tips are already possible.  Create a cylindrical tool but with a small bottom radius.
