### ISSUE TITLE
G0 rapid move not interpolated

### ISSUE THREAD

**Issue by Kerpom** [CauldronDevelopmentLLC/CAMotics#424]
On many machines, the rapid path is not interpolated. This means all axis go with the max speed independantly from each others.
Let's consider the following example:
G0 X0 Y0 Z100.0
G0 X100.0 Y40.0
In this case, the path will look in two steps.
First: both axis at max speed, the result is X40 Y40
Then the X axis keeps going up to X100 Y40.
It should be considered in case of collision detection feature.

**Comment by jcoffland** [comment]
If we had collision detection this could be an issue.  Consider adding to the discussion in #410.
