### ISSUE TITLE
Usage of Bullet physics for collision detection

### ISSUE THREAD

**Issue by Kerpom** [CauldronDevelopmentLLC/CAMotics#425]
I made a try using Bullet Physics for collision detection. 
The features of this library are of great interest in terms of performance and geometry description capabilities.
All type of tools can be modeled as compound shapes. Idem for spindle nose and chuck, fixtures and stock material.
This allows a fine grain collision detection, giving the contact points and intersection shape if needed.
I am diving in the code, aiming at integrating this feature experimentally.

**Comment by jcoffland** [comment]
Collision detection is covered by #410.  Closing as duplicate.
