### ISSUE TITLE
Please add copyright information to source files missing it

### ISSUE THREAD

**Issue by petterreinholdtsen** [CauldronDevelopmentLLC/CAMotics#430]
When running 'debmake -cc' on the source, it report several files are missing copyright information, for example config/dxflib/__init__.py and src/clipper/Clipper.cpp.  It would be easier to keep a machine generated debian/copyright if each individual file have copyright information.

**Comment by jcoffland** [comment]
``src/clipper/Clipper.cpp`` already has a copyright.  Added to others.  There are several files in the ``cairo`` folder that don't have copyrights.  I'm not sure what to put there.  The Debian build should build without using the internal ``cairo`` anyway.
