### ISSUE TITLE
Unknown NC file parsing error

### ISSUE THREAD

**Issue by jcoffland** [CauldronDevelopmentLLC/CAMotics#75]
Can someone help me with this terminal error:

ERROR:Exception: Exception @/home/wbright/NC/O100.nc:2:0
ERROR:Caused by: Expected ID_TOKEN found EOL_TOKEN

I wrote a simple *.nc file and configured only one tool, I am not able to get passed this.

I am anxious to use this software for back-plotting my code, any help would be greatly appreciated.
Thank You,
William

**Comment by rredford** [comment]
... I have same problem and that closing without explaining does not help.

**Comment by jcoffland** [comment]
If you need help you need to explain your problem in detail.  Piggybacking on a closed issue that looks similar is not the way to do it.  If you'll notice I opened the issue so I think I'm allowed to close it too.

**Comment by rredford** [comment]
It's not "similar". It's exact same line number, exact same error. Anyway it's solved.
