### ISSUE TITLE
Seg-faults on Ubuntu 12.04

### ISSUE THREAD

**Issue by WJHildreth** [CauldronDevelopmentLLC/CAMotics#86]
When installing the deb for the Linux 64bit release on Ubuntu 12.04, the software requires libv8-3.14.5 and Ubuntu 12.04 currently runs libv8-3.7.12.22.

When pulling the source and building, running the application creates a segmentation fault.  On my system it printed out the information listed at the end of this message.

On a different note, I have been learning Qt and would like to get involved in some manner in helping you.  I will send you an email.

Thanks for your time.

Joe Hildreth

14:28:47:INFO(1):************************** OpenSCAM **************************
14:28:47:INFO(1):     Website: http://openscam.org/
14:28:47:INFO(1):   Copyright: (c) 2011-2014
14:28:47:INFO(1):      Author: Joseph Coffland <joseph@openscam.org>
14:28:47:INFO(1):Organization: Cauldron Development LLC
14:28:47:INFO(1):        Args: 
14:28:47:INFO(1):      Config: <none>
14:28:47:INFO(1):*************************** Build ****************************
14:28:47:INFO(1):     Version: 0.2.5
14:28:47:INFO(1):        Date: May 14 2014
14:28:47:INFO(1):        Time: 09:23:18
14:28:47:INFO(1):  Repository: Git
14:28:47:INFO(1):    Revision: b9cab85890bb2056ea88cdf8764d3384224e3aff
14:28:47:INFO(1):      Branch: master
14:28:47:INFO(1):    Compiler: GNU 4.6.3
14:28:47:INFO(1):     Options: -std=gnu++98 -O3 -funroll-loops -mfpmath=sse -ffast-math
14:28:47:INFO(1):              -fno-unsafe-math-optimizations -msse2
14:28:47:INFO(1):    Platform: linux2 3.8.0-39-generic
14:28:47:INFO(1):        Bits: 64
14:28:47:INFO(1):        Mode: Release
14:28:47:INFO(1):*************************** System ***************************
14:28:47:INFO(1):         CPU: AMD Athlon(tm) Dual Core Processor 4850B
14:28:47:INFO(1):      CPU ID: AuthenticAMD Family 15 Model 107 Stepping 2
14:28:47:INFO(1):        CPUs: 2
14:28:47:INFO(1):      Memory: 7.80GiB
14:28:47:INFO(1): Free Memory: 4.57GiB
14:28:47:INFO(1):     Threads: POSIX_THREADS
14:28:47:INFO(1):  OS Version: 3.8
14:28:47:INFO(1): Has Battery: false
14:28:47:INFO(1):  On Battery: false
14:28:47:INFO(1):  UTC Offset: -5
14:28:47:INFO(1):         PID: 7940
14:28:47:INFO(1):         CWD: /home/joeh/OpenSCAM-src/OpenSCAM
14:28:47:INFO(1):**************************************************************
Segmentation fault (core dumped)
joeh@Joeh-IT:~/OpenSCAM-src/OpenSCAM$

**Comment by jcoffland** [comment]
Fixed in 1.0.0 release.
