### ISSUE TITLE
TPL & GCode editor

### ISSUE THREAD

**Issue by WJHildreth** [CauldronDevelopmentLLC/CAMotics#89]
I think a text editor built inside OpenSCAM to edit TPL files would be a nice addition.  Editing the TPL file outside of OpenSCAM and recalculating the paths works so you don't have to reload the file or anything.  Perhaps a right click context menu that would offer edit that would open a dockable panel for those folks that have the screen real-estate to sport it.

**Comment by jcoffland** [comment]
Fixed in 1.0.0 release.
