### ISSUE TITLE
Output G-Code in user selected units (in/mm) from TPL, etc.

### ISSUE THREAD

**Issue by WJHildreth** [CauldronDevelopmentLLC/CAMotics#90]
Currently, tplang exports g-code only in metric regardless of the units setting in the TPL program.  It would be nice to export in inches when unit is set to imperial.  The resulting g-code runs fine in OpenSCAM so this is only a cosmetic change.  Also, if a TPL program is defined as Imperial, it would be nice if the default generated tool was a .25" endmill rather than a 2mm endmill when loaded into Openscam.

**Comment by Leviathan220** [comment]
I have an issue with this implementation. So at the top of every file after running`tplang input.tpl > output.gc
` there is a G21. One could assume that by setting `units(IMPERIAL);` that this would change the beginning G21 to a G20. However, this is not the case, instead it converts your entire program into imperial values. Only one problem, I don't write my programs in metric, so the output ends up being ridiculously high numbers. I can of course simply change the G21 to a G20, which is what I have been doing.

**Comment by jcoffland** [comment]
Run it like this:

    tplang --imperial input.tpl > ouput.gc
