### ISSUE TITLE
Trackpad zoom choppy on OSX

### ISSUE THREAD

**Issue by sigxcpu76** [CauldronDevelopmentLLC/CAMotics#92]
Zoom out (using trackpad scroll) is broken in Mac OS X. It worked flawlessly in previous version.
What is does: zoom out is choppy, like it's doing 2 steps forward, 1 step back (zoom in).
What is expected to do: zoom out to be smooth, like zoom in is and like it was in the previous version.

**Comment by jcoffland** [comment]
Please test this on the new v1.2.0 release?
